#---------------------------------------------------------------------------------
.SUFFIXES:
#---------------------------------------------------------------------------------
TOPDIR ?= $(CURDIR)

#---------------------------------------------------------------------------------
# TARGET is the name of the output
# BUILDFOLDER is the directory where object files & intermediate files will be placed
# SOURCES is a list of directories containing source code
# INCLUDES is a list of directories containing header files
#---------------------------------------------------------------------------------
TARGET		:=	$(notdir $(CURDIR))
BUILDFOLDER	:=	build_linux
SOURCES		:=	source
INCLUDES	:=	include

#---------------------------------------------------------------------------------
# options for code generation
#---------------------------------------------------------------------------------
BUILD		:=	release

cflags.debug 	:=	-g -O0 -D_DEBUG
cflags.release 	:=	-g0 -O3

CFLAGS		:=	-Wall \
			-fomit-frame-pointer -ffunction-sections

CFLAGS		+=	$(INCLUDE)

CFLAGS 		+= 	${cflags.${BUILD}}

CXXFLAGS	:= 	$(CFLAGS) -fno-rtti -fno-exceptions -std=gnu++11

ldflags.debug	:=	-g -O0
ldflags.release	:=	-g0 -O3

LDFLAGS 	:=	-no-pie

LDFLAGS		+=	${ldflags.${BUILD}}

LIBS		:=	-lbftps -lpthread	

#---------------------------------------------------------------------------------
# list of directories containing libraries, this must be the top level containing
# include and lib
#---------------------------------------------------------------------------------
LIBDIRS	:= $(CURDIR)/bftps


#---------------------------------------------------------------------------------
# no real need to edit anything past this point unless you need to add additional
# rules for different file extensions
#---------------------------------------------------------------------------------
ifneq ($(BUILDFOLDER),$(notdir $(CURDIR)))
#---------------------------------------------------------------------------------
export OUTPUT	:=	$(CURDIR)/$(TARGET)
export TOPDIR	:=	$(CURDIR)

export VPATH	:=	$(foreach dir,$(SOURCES),$(CURDIR)/$(dir))

CFILES		:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.c)))
CPPFILES	:=	$(foreach dir,$(SOURCES),$(notdir $(wildcard $(dir)/*.cpp)))

#---------------------------------------------------------------------------------
# use CXX for linking C++ projects, CC for standard C
#---------------------------------------------------------------------------------
ifeq ($(strip $(CPPFILES)),)
#---------------------------------------------------------------------------------
	export LD	:=	$(CC)
#---------------------------------------------------------------------------------
else
#---------------------------------------------------------------------------------
	export LD	:=	$(CXX)
#---------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------

export OFILES_SOURCES 	:=	$(CPPFILES:.cpp=.o) $(CFILES:.c=.o)

export OFILES	:= 	$(OFILES_SOURCES)

export INCLUDE	:=	$(foreach dir,$(INCLUDES),-I$(CURDIR)/$(dir)) \
			$(foreach dir,$(LIBDIRS),-I$(dir)/include) \
			-I$(CURDIR)/$(BUILDFOLDER)

export LIBPATHS	:=	$(foreach dir,$(LIBDIRS),-L$(dir)/lib)

.PHONY: all clean
#---------------------------------------------------------------------------------
all: $(BUILDFOLDER)
	@$(MAKE) --no-print-directory -C $(BUILDFOLDER) -f $(CURDIR)/Makefile.linux
$(BUILDFOLDER):	
	@mkdir -p $@
#---------------------------------------------------------------------------------
clean:
	@echo clean linux ...
	@rm -fr $(BUILDFOLDER) $(OUTPUT)
#---------------------------------------------------------------------------------
else
#---------------------------------------------------------------------------------
# main targets
#---------------------------------------------------------------------------------
$(OUTPUT)	:  $(OFILES)  
	@$(LD) -o $@ $^ $(LDFLAGS) $(LIBPATHS) $(LIBS)
$(OFILES)	:  %.o : %.c		
	@$(LD) -o $@ -c $< $(CFLAGS)

#---------------------------------------------------------------------------------------
endif
#---------------------------------------------------------------------------------------
