.PHONY: all linux 3ds clean

all:
	@echo please choose 3ds, linux
3ds: 
	@$(MAKE) -f Makefile.3ds
linux:
	@$(MAKE) -f Makefile.linux
clean:
	@$(MAKE) -f Makefile.3ds 	clean
	@$(MAKE) -f Makefile.linux	clean
